CREATE TABLE MOVIE_INFO(
	M_SEIRAL	VARCHAR2(100) PRIMARY KEY,
	M_NAME		VARCHAR2(100),
	M_TYPE		VARCHAR2(100),
	M_RATE		VARCHAR2(100),
	M_DATE		VARCHAR2(100),
	M_GPA		VARCHAR2(100),
	M_DIRECTOR	VARCHAR2(100),
	M_ACTOR		VARCHAR2(100),
	M_THEATERTIME VARCHAR2(100),
	M_SIT		VARCHAR2(100)
);
DROP TABLE MOVIE_INFO;

INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (1,'신과함께-죄와 벌','판타지','12세 관람가','17-12-20','8.63','김용화','하정우');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (2,'차인표','코미디','15세 관람가','21-01-01','7.61','김동규','차인표');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (3,'사라져버린','액션','15세 관람가','21-01-11','6.61','피터 파시넬리','앤 헤이시');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (4,'게임의 법칙: 인간사냥','스릴러','청소년 관람불가','21-01','0','이수성','김성수');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (5,'나이브스 아웃','미스터리','12세 관람가','19-12-04','8.93','라이언 존슨','다니엘 크레이그');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (6,'더 시크릿','스릴러','15세 관람가','21-01-21','0','유발 애들러','누미 라파스');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (7,'소울','애니메이션','전체 관람가','21-01-20','9.36','피트 닥터','제이미 폭스');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (8,'아이엠 히어','로맨스','12세 관람가','21-01-14','8.5','에릭 라티고','알랭 샤바');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (9,'다만 악에서 구하소서','액션','15세 관람가','20-08-05','8.57','홍원찬','황정민');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (10,'애프터: 그 후','로맨스','15세 관람가','20-10-07','8.15','로저 컴블','히어로 파인즈 티핀');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (11,'조제, 호랑이 그리고 물고기들','애니메이션','미개봉','21-01','0','타무라 코타로','미개봉');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (12,'아무도 없었다','공포','미개봉','21-01-28','0','엘르 칼라한','아이작 제이');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (13,'사일런싱','공포','15세 관람가','21-01-28','0','로빈 프론트','니콜라이 코스터-왈도');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (14,'어벤져스: 엔드게임','액션','12세 관람가','19-04-24','9.49','안소니 루소','로버트 다우니 주니어');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (15,'나의 이름','로맨스','12세 관람가','20-10-14','7.41','허동우','전소민');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (16,'극장판 귀멸의 칼날: 무한열차편','애니메이션','15세 관람가','21-01-27','0','소토자키 하루오','하나에 나츠키');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (17,'에브리타임 아이 다이','스릴러','15세 관람가','20-10-21','5.51','로비 마이클','드류 폰티에로');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (18,'소리도 없이','범죄','15세 관람가','20-10-14','7.78','조쉬 트랭크','톰하디');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (19,'너의 결혼식','로맨스','12세 관람가','18-08-22','9.01','이석근','박보영');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (20,'운봉','액션','15세 관람가','21-01-28','0','장동현','신재범');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (21,'폰조','범죄','청소년 관람불가','20-10-14','7.78','조쉬 트랭크','톰 하디');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (22,'사냥의 시간: 데스게임','공포','청소년 관람불가','20-06-09','6','아론 미르테스','레이시 하트젤');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (23,'#살아있다','드라마','15세 관람가','20-06-24','7.03','조일형','유아인');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (24,'아이즈 온 미: 더 무비','공연 실황','전체 관람가','20-06-10','9.39','없음','권은비');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (25,'인헤리턴스','드라마','15세 관람가','20-06-25','6.08','본 스테인',' 릴리 콜린스');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (26,'열혈형사','코미디','12세 관람가','20-06-18','3.71','윤여창','김인권');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (27,'커넥트','공포','15세 관람가','21-01-20','7.64','제이콥 체이스','아지 로버트슨');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (28,'골든맨','범죄','15세 관람가','21-01-27','0','빈센조 알피리','지암파올로 모렐리');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (29,'귀여운 남자','코미디','15세 관람가','21-01-14','7.6','김정욱','신민재');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (30,'명탐정 코난: 진홍의 수학여행','애니메이션','12세 관람가','21-01-27','0','야마모토 야스이치로','야마구치 캇페이');
INSERT INTO MOVIE_INFO (M_SEIRAL, M_NAME, M_TYPE, M_RATE, M_DATE, M_GPA, M_DIRECTOR, M_ACTOR)
VALUES (31,'너는 달밤에 빛나고','로맨스','12세 관람가','20-06-10','8.43','츠키카와 쇼','키타무라 타쿠미');

COMMIT;
SELECT * FROM MOVIE_INFO;