CREATE TABLE TBL_MOVIE_INFO(
	title		VARCHAR2(500),
	rates		NUMBER(4,2),
	genre			VARCHAR2(500),
	director		VARCHAR2(500),
	actor			VARCHAR2(500)
);
DROP TABLE TBL_MOVIE_INFO;
DELETE FROM TBL_MOVIE_INFO;
SELECT * FROM TBL_MOVIE_INFO;

--SELECT M_MOVIE,M_DATE, M_TIME FROM MOVIE_INFO WHERE THEATERLO=? ORDER BY M_NAME;
-----------------
CREATE TABLE TBL_MOVIE_INFO_SOON(
	title		VARCHAR2(500),
	genre			VARCHAR2(500),
	director		VARCHAR2(500),
	actor			VARCHAR2(500)
);
DROP TABLE TBL_MOVIE_INFO_SOON;
DELETE FROM TBL_MOVIE_INFO_SOON;
SELECT * FROM TBL_MOVIE_INFO_SOON;
--
CREATE TABLE BOOK_TBL(
	title		VARCHAR2(500),
	userid			VARCHAR2(500)
);
DROP TABLE BOOK_TBL;
DELETE FROM BOOK_TBL;
SELECT * FROM BOOK_TBL;

DELETE FROM BOOK_TBL WHERE USERID='b' AND TITLE = 'a';
INSERT INTO BOOK_TBL VALUES('df','id');
SELECT * FROM BOOK_TBL WHERE USERID='id';

CREATE TABLE TBL_THEATER(
	name		VARCHAR2(500),
	sit		VARCHAR2(500),
	movie			VARCHAR2(500)
);
DROP TABLE TBL_THEATER;
DELETE FROM TBL_THEATER;
SELECT * FROM TBL_THEATER;





SELECT * FROM TBL_MOVIE_INFO ORDER BY rates DESC;

INSERT INTO TBL_MOVIE_INFO(moviename) VALUES('a');
UPDATE TBL_MOVIE_INFO SET rates = 15.75 WHERE rates IS NULL;
--INSERT INTO TBL_MOVIE_INFO
--VALUES('제목','감독','배우','개봉일','평점','상영관','상영시간','영화정보');

SELECT * FROM TBL_MOVIE_INFO;
SELECT SYSDATE FROM DUAL;
SELECT * FROM TBL_MOVIE_INFO
WHERE first_run<=SYSDATE
ORDER BY first_run;

CREATE TABLE MOVIE_TICKET(
	user_id			varchar2(200),
	movienum		NUMBER(3),
	moviename		VARCHAR2(200),
	movieprice		NUMBER(5),
	ticketamount	NUMBER(3)
);
SELECT * FROM MOVIE_TICKET;
SELECT * FROM MOVIE_TICKET WHERE user_id='A';
INSERT INTO MOVIE_TICKET
VALUES('A',1,'123',6000,100);
CREATE TABLE MOVIE_USER(
	userid			VARCHAR2(100),
	userpw			VARCHAR2(500),
	username		VARCHAR2(100),
	useremail		VARCHAR2(500),
	userphone		VARCHAR2(11),
	useraddr		VARCHAR2(300),
	userbday		VARCHAR2(100),
	usercoupon		NUMBER(5),
	usermoney		NUMBER(38),
	CONSTRAINT USERS_PK PRIMARY KEY(USERID)
);
SELECT * FROM MOVIE_USER;





CREATE SEQUENCE	MOVIENUM_SEQ
START WITH 1
MINVALUE 1
MAXVALUE 100000;

--시퀀스명.NEXTVAL : 다음 시퀀스 값
INSERT INTO LIST
VALUES(LIST_SEQ.NEXTVAL,'apple','A01');

INSERT INTO LIST
VALUES(LIST_SEQ.NEXTVAL,'banana','A02');

--시퀀스명.CURRVAL : 현재 시퀀스 값
SELECT LIST_SEQ.CURRVAL FROM DUAL;
-----------------------------------------
