CREATE TABLE MOVIE_USER(
	userid			VARCHAR2(100),
	userpw			VARCHAR2(500),
	username		VARCHAR2(100),
	useremail		VARCHAR2(500),
	userphone		VARCHAR2(11),
	useraddr		VARCHAR2(300),
	userbday		VARCHAR2(100),
	usercoupon		NUMBER(5),
	usermoney		NUMBER(38),
	CONSTRAINT USERS_PK PRIMARY KEY(USERID)
);
DROP TABLE MOVIE_USER;
DELETE FROM MOVIE_USER;
SELECT * FROM MOVIE_USER;

CREATE TABLE TBL_THEATER(
name		varchar2(500)
);
SELECT * FROM TBL_THEATER;

CREATE TABLE TBL_MOVIE_INFO(
	title		VARCHAR2(100),
	rates		NUMBER(4,2),		--//평점
	genre		VARCHAR2(500),
	director	VARCHAR2(500),
	actor		VARCHAR2(500),
	moviedate	DATE,
	theater		VARCHAR2(100),
	theatertime	VARCHAR2(10),
	movieinfo	VARCHAR2(300),
	movieprice	NUMBER(10),
	ticketamount	NUMBER(10),
	userid		VARCHAR2(100),
	theaterlo	VARCHAR2(100),
	movieserial	VARCHAR2(100),
	moviesit	VARCHAR2(100)
);
INSERT INTO TBL_MOVIE_INFO
 VALUES('a',1,'a','b','c','2021-01-28','d','e','f',8,10,'1','??','a','a');
SELECT title,moviedate, theatertime FROM TBL_MOVIE_INFO WHERE theaterlo='??';
SELECT theaterlo FROM TBL_MOVIE_INFO WHERE theaterlo='?';
DROP TABLE TBL_MOVIE_INFO;
DELETE FROM TBL_MOVIE_INFO;
SELECT * FROM TBL_MOVIE_INFO;
CREATE TABLE TBL_MOVIE_TICKET(
	user_id		VARCHAR2(100),
	moviename	VARCHAR2(100),	
	theater		VARCHAR2(100),
	theatertime	VARCHAR2(10)
);
DROP TABLE TBL_MOVIE_TICKET;
DELETE FROM TBL_MOVIE_TICKET;
SELECT * FROM TBL_MOVIE_TICKET;

CREATE TABLE TBL_MOVIE_INFO_SOON(
	title		VARCHAR2(500),
	genre		VARCHAR2(500),
	director	VARCHAR2(500),
	actor		VARCHAR2(500),
	moviedate	DATE
);
DROP TABLE TBL_MOVIE_INFO_SOON;
DELETE FROM TBL_MOVIE_INFO_SOON;
SELECT * FROM TBL_MOVIE_INFO_SOON;

CREATE TABLE BOOK_TBL(
 	title		VARCHAR2(100),
	userid		VARCHAR2(100)
);
DROP TABLE BOOK_TBL;
DELETE FROM BOOK_TBL;
SELECT * FROM BOOK_TBL;


SELECT * FROM TBL_MOVIE_INFO WHERE title IN '세자매';